# Numpy Reference
- URL : https://numpy.org/doc/stable/reference/

## list와 ndarray의 합구하기
- 4 x 4 배열의 합을 구함

In [ ]:
a1 = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
a2 = [[4,3,2,1],[1,3,2,4],[7,30,15,18],[10,19,12,18]]

print(a1)
print(a2)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[4, 3, 2, 1], [1, 3, 2, 4], [7, 30, 15, 18], [10, 19, 12, 18]]


In [ ]:
a3 = [[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]

for r in range(4):
    for c in range(4):
        a3[r][c] = a1[r][c] + a2[r][c]
        
print(a3)

[[5, 5, 5, 5], [6, 9, 9, 12], [16, 40, 26, 30], [23, 33, 27, 34]]


In [ ]:
import numpy as np

ar1 = np.array(a1)
ar2 = np.array(a2)
ar3 = ar1 + ar2
print(ar1)
print(ar2)
print(ar3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 4  3  2  1]
 [ 1  3  2  4]
 [ 7 30 15 18]
 [10 19 12 18]]
[[ 5  5  5  5]
 [ 6  9  9 12]
 [16 40 26 30]
 [23 33 27 34]]


## Numpy 속성
- .data 
- .data.obj
- .dtype 
- .astype('float')
- .shape
- .ndim
- .size
- .itemsize
- .strides

In [ ]:
ar4 = np.array(a1)
print(ar4.data)
print(ar4.data.obj)
print(ar4.dtype)
print(ar4.shape)
print(ar4.ndim)
print(ar4.size)
print(ar4.itemsize)
print(ar4.strides)
ar4=ar4.astype('float')
ar4

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
int32
(4, 4)
2
16
4
(16, 4)


array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])

In [15]:
a1 = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
a2 = [[4,3,2,1],[1,3,2,4],[7,30,15,18],[10,19,12,18]]

aa = np.array(a1)
bb = np.array(a2)


aa.dtype, bb.dtype
aa = aa.astype("float")
print(aa.dtype, bb.dtype)
print(aa.shape, bb.shape)
aa = aa.flatten()
print(aa.shape, bb.shape)


float64 int32
(4, 4) (4, 4)
(16,) (4, 4)


In [25]:
aa = aa.reshape(2,-1) # (행 개수, 열 개수)
aa



array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13., 14., 15., 16.]])

In [28]:
p  = np.arange(10)
p

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
p1 = np.zeros([5,5,5])
p1

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

## Numpy 함수
- .flatten()
- .ravel()
- .sum()
- .mean()
- .max()
- .var()
- .std()
- .copy()
- .reshape()
- .astype()

- np.array()
- np.aragne()
- np.zeros()
- np.empty()
- np.ones()
- np.linspace()
- np.logspace()

In [ ]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([5,6,7,8], dtype='float')
c = np.array([[1,2,3,4,5],[5,6,7,8,9]])
d = np.array([[1,2,3,4,5],[5,6,7,8,9]], dtype='float')

print(a.flatten(), b.flatten(), c.flatten(), d.flatten())
print(a.ravel(), b.ravel(), c.ravel(), d.ravel())

b = b.astype('int32')
print(b)

[1 2 3 4] [5. 6. 7. 8.] [1 2 3 4 5 5 6 7 8 9] [1. 2. 3. 4. 5. 5. 6. 7. 8. 9.]
[1 2 3 4] [5. 6. 7. 8.] [1 2 3 4 5 5 6 7 8 9] [1. 2. 3. 4. 5. 5. 6. 7. 8. 9.]
[5 6 7 8]


## 인덱스(Index)

In [ ]:
import numpy as np

a = [[1,2,3,4],[5,6,7,8]]
b = np.array(a) 

print(a[1][2])
print(b[1][2])
#print(a[1,2])  # 리스트에서는 [,] 인덱스 사용 불가
print(b[1,2])
print(a[0][1:3])
print(b[0][1:3])

In [2]:
a = [1,2,3,4,5,6,7,8,9,10]

for i in range(len(a)):
    a[i] *= 2

print(a)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [27]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
a * 3

aa.sum()
aa.mean()

8.5

In [38]:
p = np.linspace(0,1,7)
p

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

In [42]:
p = np.logspace(10, 0, 11)
p

array([1.e+10, 1.e+09, 1.e+08, 1.e+07, 1.e+06, 1.e+05, 1.e+04, 1.e+03,
       1.e+02, 1.e+01, 1.e+00])