## 1차원 행렬 생성

In [2]:
import numpy as np

ar1 = np.array([5,6,7,8,9])
print(ar1, ar1.shape)

ar2 = np.array([1,2,3,4,5])
print(ar2, ar2.shape)

[5 6 7 8 9] (5,)
[1 2 3 4 5] (5,)


## 1차원 행렬의 합, 차, 곱, 나누기

In [3]:
import numpy as np

ar1 = np.array([5,6,7,8,9])
print(ar1, ar1.shape)

ar2 = np.array([1,2,3,4,5])
print(ar2, ar2.shape, "\n")

print("행렬 합:", ar1 + ar2)
print("행렬 차:", ar1 - ar2)
print("행렬 곱:", ar1 * ar2)
print("행렬 나누기:", ar1 / ar2)

[5 6 7 8 9] (5,)
[1 2 3 4 5] (5,) 

행렬 합: [ 6  8 10 12 14]
행렬 차: [4 4 4 4 4]
행렬 곱: [ 5 12 21 32 45]
행렬 나누기: [5.         3.         2.33333333 2.         1.8       ]


## 2차원 행렬 생성 및 합, 차, 곱, 나누기, 수학의 행렬곱

In [4]:
import numpy as np
lst21 = [[1,2,3], [4,5,6], [7,8,9]] 
ar21= np.array(lst21) 
print(ar21, ar21.shape)
 
lst22 = [[3,2,1], [2, 3, 4], [5,4,3]]
ar22 = np.array(lst22)
print (ar22, ar22. shape, "#n")

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
[[3 2 1]
 [2 3 4]
 [5 4 3]] (3, 3) #n


In [5]:
print("행렬 합:")
print(ar21 + ar22)
print("행렬 차:")
print(ar21 - ar22)
print("행렬 곱:")
print(ar21 * ar22)
print("행렬 나누기:")
print(ar21 / ar22)


행렬 합:
[[ 4  4  4]
 [ 6  8 10]
 [12 12 12]]
행렬 차:
[[-2  0  2]
 [ 2  2  2]
 [ 2  4  6]]
행렬 곱:
[[ 3  4  3]
 [ 8 15 24]
 [35 32 27]]
행렬 나누기:
[[0.33333333 1.         3.        ]
 [2.         1.66666667 1.5       ]
 [1.4        2.         3.        ]]


In [6]:
print("행렬 곱:")
print(ar21.dot(ar22), "\n")
print("행렬 곱:")
print(np.matmul(ar21,ar22))

행렬 곱:
[[22 20 18]
 [52 47 42]
 [82 74 66]] 

행렬 곱:
[[22 20 18]
 [52 47 42]
 [82 74 66]]


## 행렬 형태 변경

In [7]:
import numpy as np
lst31 = [[1,2,3,4],[5,6,7,8]]
ar31 = np.array(lst31)
ar32 = ar31.reshape(4,2)
print(ar31, "\n")
print(ar32, "\n")
ar32.shape = (2,4)
print(ar32)

[[1 2 3 4]
 [5 6 7 8]] 

[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

[[1 2 3 4]
 [5 6 7 8]]


## 리스트로 행렬 만들기

In [8]:
import numpy as np

lst41 = list(range(10))
lst42 = list(range(0,10,2))

print(lst41)
print(lst42, "\n")

ar41 = np.array(range(0,10,3))
ar42 = np.arange(0,10,3)

print(ar41)
print(ar42, "\n")

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8] 

[0 3 6 9]
[0 3 6 9] 

