In [4]:
import numpy as np

ar1 = np.array([5,6,7,8,9])
print(ar1, ar1.shape)

ar2 = np.array([1,2,3,4,5])
print(ar2, ar2.shape)

[5 6 7 8 9] (5,)
[1 2 3 4 5] (5,)


In [5]:
print('행렬 합:', ar1 + ar2)
print('행렬 차:', ar1 - ar2)
print('행렬 곱:', ar1 * ar2)
print('행렬 나누기:', ar1 / ar2)

행렬 합: [ 6  8 10 12 14]
행렬 차: [4 4 4 4 4]
행렬 곱: [ 5 12 21 32 45]
행렬 나누기: [5.         3.         2.33333333 2.         1.8       ]


In [6]:
lst21 = [[1,2,3], [4,5,6], [7,8,9]]
ar21 = np.array(lst21)
print(ar21, ar21.shape)

lst22 = [[3,2,1], [2,3,4], [5,4,3]]
ar22 = np.array(lst22)
print(ar22, ar22.shape, '\n')


[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
[[3 2 1]
 [2 3 4]
 [5 4 3]] (3, 3) 



In [7]:
print('행렬 합:')
print(ar21 + ar22)
print('행렬 차:')
print(ar21 - ar22)
print('행렬 곱:')
print(ar21 * ar22)
print('행렬 나누기:')
print(ar21 / ar22)

행렬 합:
[[ 4  4  4]
 [ 6  8 10]
 [12 12 12]]
행렬 차:
[[-2  0  2]
 [ 2  2  2]
 [ 2  4  6]]
행렬 곱:
[[ 3  4  3]
 [ 8 15 24]
 [35 32 27]]
행렬 나누기:
[[0.33333333 1.         3.        ]
 [2.         1.66666667 1.5       ]
 [1.4        2.         3.        ]]


In [8]:
print('행렬 곱:')
print(ar21.dot(ar22), '\n')

print('행렬 곱:')
print(np.matmul(ar21, ar22))

행렬 곱:
[[22 20 18]
 [52 47 42]
 [82 74 66]] 

행렬 곱:
[[22 20 18]
 [52 47 42]
 [82 74 66]]


In [9]:
ar23 = np.array([2,4,6])
ar21 + ar23

array([[ 3,  6,  9],
       [ 6,  9, 12],
       [ 9, 12, 15]])

In [38]:
# [[3,2,1]   
# [2,3,4]
# [5,4,3]] 

# [[1,2,3]
#  [4,5,6]
#  [7,8,9]]


# [18, 24, 30]
# [42, 51, 60]
# [42, 52, 66]






In [10]:
lst31 = [[1,2,3,4], [5,6,7,8]]
ar31 = np.array(lst31)
ar32 = ar31.reshape(4,2)
print(ar31, '\n')
print(ar32, '\n')
ar32.shape = (2,4)
print(ar32)

[[1 2 3 4]
 [5 6 7 8]] 

[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
lst41 = list(range(10))
lst42 = list(range(0,10,2))
print(lst41)
print(lst42, '\n')

ar41 = np.array(range(0, 10, 3))
ar42 = np.arange(0,10,3)
print(ar41)
print(ar42, '\n')

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8] 

[0 3 6 9]
[0 3 6 9] 



In [12]:
ar43 = np.linspace(0, 10, 6)
print(ar43)
ar44 = np.logspace(2, 3, 4)
print(ar44)
ar45 = np.logspace(2, 3, num=4, base=2.0)
print(ar45)


[ 0.  2.  4.  6.  8. 10.]
[ 100.          215.443469    464.15888336 1000.        ]
[4.         5.0396842  6.34960421 8.        ]


In [13]:
ar51 = np.zeros((3,4))
ar52 = np.ones((3,4))
print(ar51, '\n')
print(ar52, '\n')

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 



In [14]:
ar53 = np.eye(5)
ar54 = np.zeros(3)
ar55 = np.ones(3)

print(ar53, '\n')
print(ar54, '\n')
print(ar55, '\n')

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

[0. 0. 0.] 

[1. 1. 1.] 



In [15]:
ar11 = np.arange(0, 100, 2)
print(ar11, '\n')

ar11.shape = (10,5)
print(ar11, '\n')

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98] 

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]
 [60 62 64 66 68]
 [70 72 74 76 78]
 [80 82 84 86 88]
 [90 92 94 96 98]] 



In [16]:
print(ar11[3], '\n')
print(ar11[3][2], '\n')
print(ar11[:3], '\n')
print(ar11[2:3:], '\n')

[30 32 34 36 38] 

34 

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]] 

[[20 22 24 26 28]] 



In [17]:
ar21 = np.array([1,2,3,4,5])
ar22 = np.array([10,20,30,40,50])
print(ar21 + 3, '\n')
print(ar21 + ar22, '\n')
print(repr(ar21), '\n')

[4 5 6 7 8] 

[11 22 33 44 55] 

array([1, 2, 3, 4, 5]) 



In [18]:
ar31 = np.array([[1,2],[3,4],[5,6]])
ar32 = ar31[[0,1,2], [0,1,0]]
ar33 = np.array([ar31[0,0], ar31[1,1], ar31[2,0]])
print(ar31, '\n')
print(ar32, '\n')
print(ar33, '\n')

[[1 2]
 [3 4]
 [5 6]] 

[1 4 5] 

[1 4 5] 



In [40]:
ar31[[0,1,2],[0,1,0]] += 10
print(ar31, '\n')

b_idx = (ar31 > 3)
print(b_idx, '\n')
print(ar31[b_idx], '\n')
print(ar31[ar31>3], '\n')

[[31  2]
 [ 3 34]
 [35  6]] 

[[ True False]
 [False  True]
 [ True  True]] 

[31 34 35  6] 

[31 34 35  6] 



In [20]:
ar41 = np.array([1,2])
ar42 = np.array([1.2, 2.3])
print(ar41.dtype)
print(ar42.dtype)

int32
float64


In [21]:
ar11 = np.array([[1,2], [3,4]], dtype=np.float64)
ar12 = np.array([[5,6], [7,9]], dtype=np.float64)
print('\n+ 연산과 add() 함수')
print(ar11 + ar12)
print(np.add(ar11, ar12))


+ 연산과 add() 함수
[[ 6.  8.]
 [10. 13.]]
[[ 6.  8.]
 [10. 13.]]


In [22]:
print('\n- 연산과 subtrack() 함수')
print(ar11 - ar12)
print(np.subtract(ar11, ar12))
print('\n+ 연산과 multiply() 함수')
print(ar11 + ar12)
print(np.multiply(ar11, ar12))
print('\n/ 연산과 divide() 함수')
print(ar11 / ar12)
print(np.divide(ar11, ar12))


- 연산과 subtrack() 함수
[[-4. -4.]
 [-4. -5.]]
[[-4. -4.]
 [-4. -5.]]

+ 연산과 multiply() 함수
[[ 6.  8.]
 [10. 13.]]
[[ 5. 12.]
 [21. 36.]]

/ 연산과 divide() 함수
[[0.2        0.33333333]
 [0.42857143 0.44444444]]
[[0.2        0.33333333]
 [0.42857143 0.44444444]]


In [23]:
print('\nsqrt()함수')
print(np.sqrt(ar11), '\n')


sqrt()함수
[[1.         1.41421356]
 [1.73205081 2.        ]] 



In [24]:
print('\ndot()함수')
print(ar11.dot(ar12), '\n')
print(np.dot(ar11,ar12), '\n')


dot()함수
[[19. 24.]
 [43. 54.]] 

[[19. 24.]
 [43. 54.]] 



In [25]:
print('\nsum()함수')
print(np.sum(ar11), '\n')
print(np.sum(ar11, axis=0), '\n')
print(np.sum(ar11, axis=1), '\n')

print('\n전치행렬')
print(ar11.T, '\n')


sum()함수
10.0 

[4. 6.] 

[3. 7.] 


전치행렬
[[1. 3.]
 [2. 4.]] 



In [26]:
ar21 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
ar22 = np.array([1,0,1])
ar29 = np.empty_like(ar21)
for i in range(4):
  ar29[i, :] = ar21[i, :] + ar22

print(ar21, '\n')
print(ar22, '\n')
print(ar29, '\n')


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[1 0 1] 

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]] 

